{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Colab RDP.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/PradyumnaKrishna/Colab-Hacks/blob/master/Colab%20RDP/Colab%20RDP.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "iLh_9SkSut4u"
      },
      "source": [
        "# **Colab RDP** : Remote Desktop to Colab Instance\n",
        "\n",
        "> **Warning : Not for Cryptocurrency Mining<br></br>** \n",
        ">**Why are hardware resources such as T4 GPUs not available to me?** The best available hardware is prioritized for users who use Colaboratory interactively rather than for long-running computations. Users who use Colaboratory for long-running computations may be temporarily restricted in the type of hardware made available to them, and/or the duration that the hardware can be used for. We encourage users with high computational needs to use Colaboratory’s UI with a local runtime. Please note that using Colaboratory for cryptocurrency mining is disallowed entirely, and may result in being banned from using Colab altogether.\n",
        "\n",
        "Google Colab can give you Instance with 12GB of RAM and GPU for 12 hours (Max.) for Free users. Anyone can use it to perform Heavy Tasks.\n",
        "\n",
        "To use other similiar Notebooks use my Repository **[Colab Hacks](https://github.com/PradyumnaKrishna/Colab-Hacks)**"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "t4yNp3KmLtZ6",
        "cellView": "form"
      },
      "source": [
        "#@title **Create User**\n",
        "#@markdown Enter Username and Password\n",
        "\n",
        "import os\n",
        "\n",
        "username = \"user\" #@param {type:\"string\"}\n",
        "password = \"root\" #@param {type:\"string\"}\n",
        "\n",
        "print(\"Creating User and Setting it up\")\n",
        "\n",
        "# Creation of user\n",
        "os.system(f\"useradd -m {username}\")\n",
        "\n",
        "# Add user to sudo group\n",
        "os.system(f\"adduser {username} sudo\")\n",
        "    \n",
        "# Set password of user to 'root'\n",
        "os.system(f\"echo '{username}:{password}' | sudo chpasswd\")\n",
        "\n",
        "# Change default shell from sh to bash\n",
        "os.system(\"sed -i 's/\\/bin\\/sh/\\/bin\\/bash/g' /etc/passwd\")\n",
        "\n",
        "print(f\"User created and configured having username `{username}` and password `{password}`\")"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Q6bl1b0EifVG",
        "cellView": "form"
      },
      "source": [
        "#@title **RDP**\n",
        "#@markdown  It takes 4-5 minutes for installation\n",
        "\n",
        "import os\n",
        "import subprocess\n",
        "\n",
        "#@markdown  Visit http://remotedesktop.google.com/headless and copy the command after Authentication\n",
        "\n",
        "CRP = \"\" #@param {type:\"string\"}\n",
        "\n",
        "#@markdown Enter a Pin (more or equal to 6 digits)\n",
        "Pin = 123456 #@param {type: \"integer\"}\n",
        "\n",
        "#@markdown Autostart Notebook in RDP\n",
        "Autostart = False #@param {type: \"boolean\"}\n",
        "\n",
        "\n",
        "class CRD:\n",
        "    def __init__(self, user):\n",
        "        os.system(\"apt update\")\n",
        "        self.installCRD()\n",
        "        self.installDesktopEnvironment()\n",
        "        self.installGoogleChorme()\n",
        "        self.finish(user)\n",
        "        print(\"\\nRDP created succesfully move to https://remotedesktop.google.com/access\")\n",
        "\n",
        "    @staticmethod\n",
        "    def installCRD():\n",
        "        print(\"Installing Chrome Remote Desktop\")\n",
        "        subprocess.run(['wget', 'https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb'], stdout=subprocess.PIPE)\n",
        "        subprocess.run(['dpkg', '--install', 'chrome-remote-desktop_current_amd64.deb'], stdout=subprocess.PIPE)\n",
        "        subprocess.run(['apt', 'install', '--assume-yes', '--fix-broken'], stdout=subprocess.PIPE)\n",
        "\n",
        "    @staticmethod\n",
        "    def installDesktopEnvironment():\n",
        "        print(\"Installing Desktop Environment\")\n",
        "        os.system(\"export DEBIAN_FRONTEND=noninteractive\")\n",
        "        os.system(\"apt install --assume-yes xfce4 desktop-base xfce4-terminal\")\n",
        "        os.system(\"bash -c 'echo \\\"exec /etc/X11/Xsession /usr/bin/xfce4-session\\\" > /etc/chrome-remote-desktop-session'\")\n",
        "        os.system(\"apt remove --assume-yes gnome-terminal\")\n",
        "        os.system(\"apt install --assume-yes xscreensaver\")\n",
        "        os.system(\"systemctl disable lightdm.service\")\n",
        "\n",
        "    @staticmethod\n",
        "    def installGoogleChorme():\n",
        "        print(\"Installing Google Chrome\")\n",
        "        subprocess.run([\"wget\", \"https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb\"], stdout=subprocess.PIPE)\n",
        "        subprocess.run([\"dpkg\", \"--install\", \"google-chrome-stable_current_amd64.deb\"], stdout=subprocess.PIPE)\n",
        "        subprocess.run(['apt', 'install', '--assume-yes', '--fix-broken'], stdout=subprocess.PIPE)\n",
        "\n",
        "    @staticmethod\n",
        "    def finish(user):\n",
        "        print(\"Finalizing\")\n",
        "        if Autostart:\n",
        "            os.makedirs(f\"/home/{user}/.config/autostart\", exist_ok=True)\n",
        "            link = \"https://colab.research.google.com/github/PradyumnaKrishna/Colab-Hacks/blob/master/Colab%20RDP/Colab%20RDP.ipynb\"\n",
        "            colab_autostart = \"\"\"[Desktop Entry]\n",
        "Type=Application\n",
        "Name=Colab\n",
        "Exec=sh -c \"sensible-browser {}\"\n",
        "Icon=\n",
        "Comment=Open a predefined notebook at session signin.\n",
        "X-GNOME-Autostart-enabled=true\"\"\".format(link)\n",
        "            with open(f\"/home/{user}/.config/autostart/colab.desktop\", \"w\") as f:\n",
        "                f.write(colab_autostart)\n",
        "            os.system(f\"chmod +x /home/{user}/.config/autostart/colab.desktop\")\n",
        "            os.system(f\"chown {user}:{user} /home/{user}/.config\")\n",
        "\n",
        "        os.system(f\"adduser {user} chrome-remote-desktop\")\n",
        "        command = f\"{CRP} --pin={Pin}\"\n",
        "        os.system(f\"su - {user} -c '{command}'\")\n",
        "        os.system(\"service chrome-remote-desktop start\")\n",
        "        \n",
        "\n",
        "        print(\"Finished Succesfully\")\n",
        "\n",
        "\n",
        "try:\n",
        "    if CRP == \"\":\n",
        "        print(\"Please enter authcode from the given link\")\n",
        "    elif len(str(Pin)) < 6:\n",
        "        print(\"Enter a pin more or equal to 6 digits\")\n",
        "    else:\n",
        "        CRD(username)\n",
        "except NameError as e:\n",
        "    print(\"'username' variable not found, Create a user first\")"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "vk2qtOTGIFsQ",
        "cellView": "form"
      },
      "source": [
        "%env USE_AUTH_EPHEM=0\n",
        "\n",
        "#@title **Google Drive Mount**\n",
        "#@markdown Google Drive can be used as Persistance HDD for files.<br>\n",
        "\n",
        "#@markdown **Choose a method (GDFuse Recommended)**\n",
        "mount_method = \"GDFuse\" #@param [\"GDFuse\", \"Native\"]\n",
        "\n",
        "\n",
        "#@markdown **Options for GDFuse** <br>\n",
        "#@markdown - Visit https://github.com/astrada/google-drive-ocamlfuse/wiki/Team-Drives\n",
        "label = \"default\" #@param {type:\"string\"}\n",
        "mount_team_drive = False #@param {type:\"boolean\"}\n",
        "force_mount = False #@param {type:\"boolean\"}\n",
        "\n",
        "import os\n",
        "import subprocess\n",
        "\n",
        "\n",
        "class Drive():\n",
        "    creds = {}\n",
        "    mountpoint = \"\"\n",
        "    deps = False\n",
        "    \n",
        "    debug = False\n",
        "\n",
        "    def __init__(self, mountpoint=\"/content/drives\", debug=False):\n",
        "        os.makedirs(mountpoint, exist_ok=True)\n",
        "        self.mountpoint = mountpoint\n",
        "        self.debug = debug\n",
        "\n",
        "    def _mount_gdfuse(self, mount_dir):\n",
        "        os.makedirs(mount_dir, exist_ok=True)\n",
        "\n",
        "        subprocess.run(\n",
        "            ['google-drive-ocamlfuse',\n",
        "             '-o',\n",
        "             'allow_other',\n",
        "             '-label',\n",
        "             label,\n",
        "             mount_dir,\n",
        "            ]\n",
        "        )\n",
        "\n",
        "        print(f\"Drive Mounted at {mount_dir}. If you get input/output error, then `team_drive_id` might be wrong or not accessible.\")\n",
        "\n",
        "    def _unmount_gdfuse(self, mount_dir):\n",
        "        subprocess.run(\n",
        "            ['fusermount',\n",
        "             '-u',\n",
        "             mount_dir,\n",
        "            ]\n",
        "        )\n",
        "        os.rmdir(mount_dir)\n",
        "\n",
        "    def auth(self):\n",
        "        from google.colab import auth\n",
        "        from oauth2client.client import GoogleCredentials\n",
        "\n",
        "        auth.authenticate_user()\n",
        "        \n",
        "        creds = GoogleCredentials.get_application_default()\n",
        "        self.creds = {\n",
        "            \"id\": creds.client_id,\n",
        "            \"secret\": creds.client_secret\n",
        "        }\n",
        "\n",
        "    def gdfuse(self, label, mound_team_drive=False, force_mount=False):\n",
        "        import getpass\n",
        "\n",
        "        if not self.creds:\n",
        "            self.auth()\n",
        "\n",
        "        if not self.deps:\n",
        "            print(\"Installing google-drive-ocamlfuse\")\n",
        "            subprocess.run(['apt', 'install', 'software-properties-common python-software-properties module-init-tools', '-y'])\n",
        "            subprocess.run(['add-apt-repository', 'ppa:alessandro-strada/ppa', '-y'])\n",
        "            subprocess.run(['apt', 'update'])\n",
        "            subprocess.run(['apt', 'install', '--assume-yes', 'google-drive-ocamlfuse'])\n",
        "            self.deps = True\n",
        "\n",
        "        base_dir = '/root/.gdfuse'\n",
        "        config_dir = f'{base_dir}/{label}'\n",
        "        mount_dir = f\"{self.mountpoint}/{label}\"\n",
        "\n",
        "        if force_mount and os.path.exists(mount_dir):\n",
        "            self._unmount_gdfuse(mount_dir)\n",
        "        elif os.path.exists(mount_dir):\n",
        "            print(\"Drive already mounted\")\n",
        "            return\n",
        "\n",
        "        if not os.path.exists(config_dir) or force_mount:\n",
        "            print(f\"Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id={self.creds['id']}&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force\")\n",
        "            vcode = getpass.getpass(\"Enter the Auth Code: \")\n",
        "\n",
        "            subprocess.run(\n",
        "              ['google-drive-ocamlfuse',\n",
        "                '-headless',\n",
        "                '-id',\n",
        "                self.creds['id'],\n",
        "                '-secret',\n",
        "                self.creds['secret'],\n",
        "                '-label',\n",
        "                label,\n",
        "              ],\n",
        "                text=True,\n",
        "                input=vcode\n",
        "            )\n",
        "\n",
        "        if mount_team_drive:\n",
        "            team_drive_id = input(\"Enter Team Drive ID: \")\n",
        "\n",
        "            subprocess.run(\n",
        "                ['sed',\n",
        "                 '-i',\n",
        "                 f's/team_drive_id=.*$/team_drive_id={team_drive_id}/g',\n",
        "                 f'{config_dir}/config'\n",
        "                ]\n",
        "            )\n",
        "        else:\n",
        "            subprocess.run(\n",
        "                ['sed',\n",
        "                 '-i',\n",
        "                 f's/team_drive_id=.*$/team_drive_id=/g',\n",
        "                 f'{config_dir}/config'\n",
        "                ]\n",
        "            )\n",
        "\n",
        "        self._mount_gdfuse(mount_dir)\n",
        "\n",
        "\n",
        "    def native(self):\n",
        "        from google.colab import drive\n",
        "        mount_dir = f\"{self.mountpoint}/Native\"\n",
        "        drive.mount(mount_dir)\n",
        "\n",
        "if 'drive' not in globals():\n",
        "    try:\n",
        "        drive = Drive(f\"/home/{username}/drives\")\n",
        "    except NameError:\n",
        "        drive = Drive('/content/drives')\n",
        "\n",
        "if mount_method == \"Native\":\n",
        "    drive.native()\n",
        "if mount_method == \"GDFuse\":\n",
        "    drive.gdfuse(label, mount_team_drive, force_mount)\n"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "8icuQYnyKDLk",
        "cellView": "form"
      },
      "source": [
        "#@title **SSH**\n",
        "\n",
        "! pip install colab_ssh --upgrade &> /dev/null\n",
        "\n",
        "#@markdown Choose a method (Agro Recommended)\n",
        "ssh_method = \"Agro\" #@param [\"Agro\", \"Ngrok\"]\n",
        "\n",
        "\n",
        "#@markdown Copy authtoken from https://dashboard.ngrok.com/auth (only for ngrok)\n",
        "ngrokRegion = \"us\" #@param [\"us\", \"eu\", \"ap\", \"au\", \"sa\", \"jp\", \"in\"]\n",
        "\n",
        "def runAgro():\n",
        "    from colab_ssh import launch_ssh_cloudflared\n",
        "    launch_ssh_cloudflared(password=password)\n",
        "\n",
        "def runNgrok():\n",
        "    from colab_ssh import launch_ssh\n",
        "    from IPython.display import clear_output\n",
        "\n",
        "    import getpass\n",
        "    ngrokToken = getpass.getpass(\"Enter the ngrokToken: \")\n",
        "\n",
        "    launch_ssh(ngrokToken, password, region=ngrokRegion)\n",
        "    clear_output()\n",
        "\n",
        "    print(\"ssh\", user, end='@')\n",
        "    ! curl -s http://localhost:4040/api/tunnels | python3 -c \\\n",
        "            \"import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'][6:].replace(':', ' -p '))\"\n",
        "\n",
        "try:\n",
        "    user = username\n",
        "    password = password\n",
        "except NameError:\n",
        "    print(\"No user found, using username and password as 'root'\")\n",
        "    user='root'\n",
        "    password='root'\n",
        "\n",
        "\n",
        "if ssh_method == \"Agro\":\n",
        "    runAgro()\n",
        "if ssh_method == \"Ngrok\":\n",
        "    runNgrok()"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "UoeBdz6_KE6a",
        "cellView": "form"
      },
      "source": [
        "#@title **Colab Shutdown**\n",
        "\n",
        "#@markdown To Kill NGROK Tunnel\n",
        "NGROK = False #@param {type:'boolean'}\n",
        "\n",
        "#@markdown To Sleep Colab\n",
        "Sleep = True #@param {type:'boolean'}\n",
        "\n",
        "if NGROK:\n",
        "    ! killall ngrok\n",
        "\n",
        "if Sleep:\n",
        "    from time import sleep\n",
        "    sleep(43200)"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}